"""
Django settings for ecom_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-bcfe9k+zzd0$^i_msvjral^4@bwu)(5cwdj^-t$8e+^f)m!6fz')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "accept",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',

    'master',
    'customer',
    'shared',
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'ecom_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'ecom_backend.wsgi.application'
ASGI_APPLICATION = 'ecom_backend.asgi.application'

# WebSocket (weighing scale on barcode screen)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_ACCESS_SECRET_KEY_ID")
AWS_REGION = os.getenv("AWS_REGION")
AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
# Optional: public base for product image URLs (e.g. https://cdn.example.com or CloudFront). Falls back to S3 virtual-host URL.
AWS_S3_PUBLIC_BASE_URL = os.getenv("AWS_S3_PUBLIC_BASE_URL", "").strip() or None
AWS_S3_BASE_URL = os.getenv("AWS_S3_BASE_URL", "").strip() or None
# ICICI Orange / PhiCommerce PG (CP Card/NB/UPI one-time pay)
ORANGE_PG_MERCHANT_ID = os.getenv("ORANGE_PG_MERCHANT_ID", "")
ORANGE_PG_AGGREGATOR_ID = os.getenv("ORANGE_PG_AGGREGATOR_ID", "")
ORANGE_PG_SECRET_KEY = os.getenv("ORANGE_PG_SECRET_KEY", "")
ORANGE_PG_INITIATE_URL = os.getenv(
    "ORANGE_PG_INITIATE_URL",
    "https://pgpayuat.icicibank.com/tsp/pg/api/v2/initiateSale",
)
ORANGE_PG_COMMAND_URL = os.getenv(
    "ORANGE_PG_COMMAND_URL",
    "https://pgpayuat.icicibank.com/tsp/pg/api/command",
)
# Absolute URL bank POSTs to after payment (backend). Override in .env for each env.
ORANGE_PG_RETURN_URL = os.getenv("ORANGE_PG_RETURN_URL", "")
# Where backend redirects the browser after return (customer hub SPA — not admin)
ORANGE_PG_HUB_RETURN_BASE = os.getenv(
    "ORANGE_PG_HUB_RETURN_BASE",
    "http://127.0.0.1:8080/payment-status",
)
OTPMSG_USER = os.getenv("OTPMSG_USER")
OTPMSG_PASSWORD = os.getenv("OTPMSG_PASSWORD")
OTPMSG_API_KEY = os.getenv("OTPMSG_API_KEY") or os.getenv("OTPMSG_APIKEY")
OTPMSG_SENDER_ID = os.getenv("OTPMSG_SENDER_ID", "SOHEES")
OTPMSG_TEMPLATE_ID = os.getenv("OTPMSG_DLT_TEMPLATE_ID")
OTPMSG_ROUTE = int(os.getenv("OTPMSG_ROUTE", "1"))
OTPMSG_DCS = int(os.getenv("OTPMSG_DCS", "8"))
OTPMSG_ENTITY_ID = os.getenv("OTPMSG_ENTITY_ID", "")

# DLT template IDs (otpmsg.in / Ashish Jewellers)
SMS_DLT_LOGIN_OTP = os.getenv("SMS_DLT_LOGIN_OTP", "1777178644803861286")
SMS_DLT_OUTSTANDING_BALANCE = os.getenv("SMS_DLT_OUTSTANDING_BALANCE", "1777178636239869925")
SMS_DLT_ADVANCE_RECEIPT = os.getenv("SMS_DLT_ADVANCE_RECEIPT", "1777178636191895435")
SMS_DLT_SCHEME_DUE_REMINDER = os.getenv("SMS_DLT_SCHEME_DUE_REMINDER", "1777178636104573799")
SMS_DLT_UDHAR_REMINDER = os.getenv("SMS_DLT_UDHAR_REMINDER", "1777178636123117186")
SMS_DLT_GOLD_RATE = os.getenv("SMS_DLT_GOLD_RATE", "1777178636642002888")

PAYMENT_SUCCESS_TEMPLATE_ID = os.getenv("PAYMENT_SUCCESS_TEMPLATE_ID")

# Mart2Meta WhatsApp API
WHATSAPP_UID = os.getenv("WHATSAPP_UID", "")
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_API_TOKEN = os.getenv("WHATSAPP_API_TOKEN", "")
# Approved Meta template (Mart2Meta dashboard)
WHATSAPP_TEMPLATE_LANGUAGE = os.getenv("WHATSAPP_TEMPLATE_LANGUAGE", "en_US")
WHATSAPP_TEMPLATE_INVOICE = os.getenv("WHATSAPP_TEMPLATE_INVOICE", "testtemplate")
WHATSAPP_TEMPLATE_SCHEME_REMINDER = os.getenv("WHATSAPP_TEMPLATE_SCHEME_REMINDER", "testtemplate")
WHATSAPP_TEMPLATE_OFFER = os.getenv(
    "WHATSAPP_TEMPLATE_OFFER",
    os.getenv("WHATSAPP_TEMPLATE_SCHEME_REMINDER", "testtemplate"),
)

# -----------------------------------------------------------------------------
# ICICI UPI — URLs from Mandate Collect PDF + QR/Intent PDF
#
# PDF hosts (default when ICICI_API_BASE is empty):
#   UAT:  https://apibankingonesandbox.icicibank.com
#   Live: https://apibankingone.icicibank.com
# Client may override ICICI_API_BASE (e.g. *.icici.bank.in).
# Every endpoint URL below can also be overridden in .env.
#
# Encryption (QR API PDF): Hybrid (default) or Asymmetric
#   Hybrid: RSA(sessionKey) + AES/CBC/PKCS5 + apikey header
#   Asymmetric: RSA body as text/plain
# -----------------------------------------------------------------------------
ICICI_MERCHANT_ID = os.getenv("ICICI_MERCHANT_ID", "").strip()
ICICI_SUB_MERCHANT_ID = (
    os.getenv("ICICI_SUB_MERCHANT_ID", "").strip() or ICICI_MERCHANT_ID
)
# Mandate Collect PDF: terminalId = MCC (client gave 6012 for jewellery)
ICICI_TERMINAL_ID = os.getenv("ICICI_TERMINAL_ID", "6012").strip() or "6012"
# QR API PDF: terminalId default MCC 5411 for QR3 / Intent
ICICI_UPI_MCC = os.getenv("ICICI_UPI_MCC", "5411").strip() or "5411"
ICICI_MERCHANT_NAME = os.getenv("ICICI_MERCHANT_NAME", "One Ashish").strip() or "One Ashish"
ICICI_SUB_MERCHANT_NAME = (
    os.getenv("ICICI_SUB_MERCHANT_NAME", "Jewellery Scheme").strip() or "Jewellery Scheme"
)
ICICI_MERCHANT_VPA = os.getenv("ICICI_MERCHANT_VPA", "").strip()
ICICI_API_KEY = os.getenv("ICICI_API_KEY", "").strip()
ICICI_CALLBACK_URL = os.getenv("ICICI_CALLBACK_URL", "").strip()
ICICI_CALLBACK_SECRET = os.getenv("ICICI_CALLBACK_SECRET", "").strip()

# Hybrid | Asymmetric | None  (bank mail = Hybrid)
ICICI_ENCRYPTION_MODE = os.getenv("ICICI_ENCRYPTION_MODE", "Hybrid").strip() or "Hybrid"
# Bank public cert (.pem/.cer) — encrypt outbound (both modes)
ICICI_BANK_PUBLIC_KEY_PATH = os.getenv(
    "ICICI_BANK_PUBLIC_KEY_PATH",
    str(BASE_DIR / "certs" / "icici" / "icici_bank_public.pem"),
).strip()
# Merchant private key — decrypt bank Hybrid/Asymmetric responses + callbacks
ICICI_MERCHANT_PRIVATE_KEY_PATH = os.getenv("ICICI_MERCHANT_PRIVATE_KEY_PATH", "").strip()
ICICI_MERCHANT_PRIVATE_KEY_PASSWORD = os.getenv("ICICI_MERCHANT_PRIVATE_KEY_PASSWORD", "").strip()
# Hybrid wrapper "service" — PDF marks this mandatory. UPI mandate APIs use "UPI".
ICICI_HYBRID_SERVICE = os.getenv("ICICI_HYBRID_SERVICE", "UPI").strip() or "UPI"
# PDF Hybrid step 1: "Generate 16-digit random number (session key)" — digit|hex, len 16|32
ICICI_HYBRID_SESSION_KEY_LEN = int(os.getenv("ICICI_HYBRID_SESSION_KEY_LEN", "16") or "16")
ICICI_HYBRID_SESSION_KEY_STYLE = (
    os.getenv("ICICI_HYBRID_SESSION_KEY_STYLE", "digit").strip() or "digit"
)
# PDF Hybrid: IV = Base64(RANDOMNO)[:16]; package as prepend (PDF sample) or field
ICICI_HYBRID_IV_MODE = os.getenv("ICICI_HYBRID_IV_MODE", "prepend").strip() or "prepend"

ICICI_HOST_BY_ENV = {
    "sandbox": "https://apibankingonesandbox.icicibank.com",
    "uat": "https://apibankingonesandbox.icici.bank.in",
    "prod": "https://apibankingone.icici.bank.in",
    "production": "https://apibankingone.icici.bank.in",
}
ICICI_ENV = (os.getenv("ICICI_ENV") or "uat").strip().lower()
ICICI_API_BASE = (
    os.getenv("ICICI_API_BASE") or ICICI_HOST_BY_ENV.get(ICICI_ENV, ICICI_HOST_BY_ENV["uat"])
).strip().rstrip("/")


def _icici_api(path: str) -> str:
    """Build full ICICI URL from ICICI_API_BASE. Empty when MID/base/path missing."""
    if not path or not ICICI_MERCHANT_ID or not ICICI_API_BASE:
        return ""
    return f"{ICICI_API_BASE}{path}"


def _icici_url(env_key: str, path: str) -> str:
    """Env override wins; else PDF path on ICICI_API_BASE."""
    override = os.getenv(env_key, "").strip()
    if override:
        return override
    return _icici_api(path)


# ---------------------------------------------------------------------------
# QR / Intent API PDF — UPI/v0 (one-time pay Intent + Scan QR)
# UAT:  …/sandbox…/api/MerchantAPI/UPI/v0/…
# Live: …/apibankingone…/api/MerchantAPI/UPI/v0/…
# ---------------------------------------------------------------------------
_mid = ICICI_MERCHANT_ID
ICICI_UPI_QR3_URL = _icici_url(
    "ICICI_UPI_QR3_URL", f"/api/MerchantAPI/UPI/v0/QR3/{_mid}" if _mid else ""
)
ICICI_UPI_TXN_STATUS3_URL = _icici_url(
    "ICICI_UPI_TXN_STATUS3_URL",
    f"/api/MerchantAPI/UPI/v0/TransactionStatus3/{_mid}" if _mid else "",
)
ICICI_UPI_CALLBACK_STATUS2_URL = _icici_url(
    "ICICI_UPI_CALLBACK_STATUS2_URL",
    f"/api/MerchantAPI/UPI/v0/CallbackStatus2/{_mid}" if _mid else "",
)
ICICI_UPI_REFUND_URL = _icici_url(
    "ICICI_UPI_REFUND_URL", f"/api/MerchantAPI/UPI/v0/Refund/{_mid}" if _mid else ""
)

# ---------------------------------------------------------------------------
# Mandate Collect PDF — UPI2 (AutoPay Collect / Execute / Status)
# + MandateQR (client mail; not listed in Collect PDF body)
# ---------------------------------------------------------------------------
ICICI_CREATE_MANDATE_URL = _icici_url(
    "ICICI_CREATE_MANDATE_URL", "/api/MerchantAPI/UPI2/v1/CreateMandate"
)
ICICI_NOTIFICATION_URL = _icici_url(
    "ICICI_NOTIFICATION_URL", "/api/MerchantAPI/UPI2/v1/MandateNotification"
)
ICICI_EXECUTE_MANDATE_URL = _icici_url(
    "ICICI_EXECUTE_MANDATE_URL", "/api/MerchantAPI/UPI2/v1/ExecuteMandate"
)
# Revoke + Update use CreateMandate URL with requestType R / U (Collect PDF §4–5)
ICICI_REVOKE_MANDATE_URL = _icici_url(
    "ICICI_REVOKE_MANDATE_URL", "/api/MerchantAPI/UPI2/v1/CreateMandate"
)
ICICI_UPDATE_MANDATE_URL = _icici_url(
    "ICICI_UPDATE_MANDATE_URL", "/api/MerchantAPI/UPI2/v1/CreateMandate"
)
ICICI_TRANSACTION_STATUS_URL = _icici_url(
    "ICICI_TRANSACTION_STATUS_URL", "/api/MerchantAPI/UPI2/v1/TransactionStatus"
)
ICICI_TRANSACTION_STATUS_BY_CRITERIA_URL = _icici_url(
    "ICICI_TRANSACTION_STATUS_BY_CRITERIA_URL",
    "/api/MerchantAPI/UPI2/v1/TransactionStatusByCriteria",
)
ICICI_MANDATE_QR_URL = _icici_url(
    "ICICI_MANDATE_QR_URL", "/api/MerchantAPI/UPI2/v1/MandateQR"
)

# onetime = UPI/v0 QR3 (pay once). mandate = UPI2 MandateQR / CreateMandate (AutoPay).
ICICI_UPI_QR_MODE = (os.getenv("ICICI_UPI_QR_MODE", "mandate") or "mandate").strip().lower()

# true = fake approve/pay after ~6s (dev only). false = real bank calls.
ICICI_MANDATE_SIMULATE = os.getenv(
    "ICICI_MANDATE_SIMULATE",
    "true" if DEBUG else "false",
).lower() == "true"


DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'jewelry_ecom'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Authentication settings
AUTHENTICATION_BACKENDS = []

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
}

# JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '60'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '1'))),
    'ROTATE_REFRESH_TOKENS': os.getenv('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() == 'true',
    'BLACKLIST_AFTER_ROTATION': os.getenv('JWT_BLACKLIST_AFTER_ROTATION', 'True').lower() == 'true',
    'ALGORITHM': os.getenv('JWT_ALGORITHM', 'HS256'),
    'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY', 'django-insecure-bcfe9k+zzd0$^i_msvjral^4@bwu)(5cwdj^-t$8e+^f)m!6fz'),
    'AUTH_HEADER_TYPES': ('Bearer',),
}
