"""Shared @admin_auth permission tuples for metal read APIs (masters + stores)."""

STORE_METAL_READ_AUTH = (
    "CRM_STORES_METAL_CONFIGURATION",
    "CRM_STORES_METAL_RATE",
    "CRM_STORES_METAL_CONFIG",
    "CRM_STORES_METAL_RULES",
    "CRM_STORES_METALS_RATE_VIEW",
    "CRM_STORES_METALS_CONFIG_VIEW",
    "CRM_STORES",
)

MASTER_METAL_READ_AUTH = (
    "CRM_MASTERS_METAL_VIEW",
    "CRM_MASTERS_DAILY_GOLD_RATES_VIEW",
    "CRM_MASTERS_METALS_VIEW",
    "CRM_MASTERS_METALS_RATE_VIEW",
    "CRM_MASTERS_METALS_RULE_VIEW",
)

METAL_LIST_READ_AUTH = MASTER_METAL_READ_AUTH + STORE_METAL_READ_AUTH

# Role-UI section codes — direct match when prod has not deployed permission_aliases yet.
MASTER_METAL_SECTION_READ_AUTH = (
    "CRM_METALS",
    "CRM_METALS_VIEW",
    "CRM_MASTERS_METALS_VIEW",
    "CRM_METAL_RATE",
    "CRM_METAL_RATE_VIEW",
    "CRM_MASTERS_METALS_RATE_VIEW",
    "CRM_METAL_RULE",
    "CRM_METAL_RULE_VIEW",
    "CRM_MASTERS_METALS_RULE_VIEW",
    "CRM_MASTERS_GOLD_RATE_RULES",
    "CRM_MASTERS_GOLD_RATE_RULES_VIEW",
)

METAL_RULE_READ_AUTH = METAL_LIST_READ_AUTH + MASTER_METAL_SECTION_READ_AUTH

# Master (HO) metal rate create/update — prod DB uses CRM_MASTERS_METALS_RATE_* codes.
MASTER_METAL_WRITE_AUTH = (
    "CRM_MASTERS_METAL_VIEW",
    "CRM_MASTERS_DAILY_GOLD_RATES_UPDATE",
    "CRM_MASTERS_METALS_RATE_UPDATE",
    "CRM_MASTERS_METALS_RATE_CREATE",
    "CRM_METAL_RATE_UPDATE",
    "CRM_METAL_RATE_CREATE",
)

# Master (HO) metal rule create/update/delete — prod DB uses CRM_MASTERS_METALS_RULE_* codes.
MASTER_METAL_RULE_WRITE_AUTH = (
    "CRM_MASTERS_METAL_VIEW",
    "CRM_MASTERS_DAILY_GOLD_RATES_UPDATE",
    "CRM_MASTERS_METALS_RULE_UPDATE",
    "CRM_MASTERS_METALS_RULE_CREATE",
    "CRM_MASTERS_METALS_RULE_DELETE",
    "CRM_METAL_RULE_UPDATE",
    "CRM_METAL_RULE_CREATE",
    "CRM_METAL_RULE_DELETE",
    "CRM_MASTERS_GOLD_RATE_RULES_UPDATE",
    "CRM_MASTERS_GOLD_RATE_RULES_CREATE",
    "CRM_MASTERS_GOLD_RATE_RULES_DELETE",
)

# Store branch metal rate create/update — prod DB uses CRM_STORES_METALS_RATE_* codes.
STORE_METAL_RATE_WRITE_AUTH = (
    "CRM_STORES_METALS_RATE_UPDATE",
    "CRM_STORES_METALS_RATE_CREATE",
    "CRM_STORES_METAL_RATE_UPDATE",
    "CRM_STORES_METAL_RATE_CREATE",
    "CRM_STORES_METAL_RATES_UPDATE",
    "CRM_STORES_METAL_RATES_CREATE",
    "CRM_STORES_DAILY_GOLD_RATES_UPDATE",
    "CRM_STORES_DAILY_GOLD_RATES_CREATE",
)

# Branch rate PUT: master HO writers or store metal rate writers.
METAL_BRANCH_RATE_WRITE_AUTH = MASTER_METAL_WRITE_AUTH + STORE_METAL_RATE_WRITE_AUTH + (
    "CRM_STORES_METALS_CONFIG_UPDATE",
    "CRM_STORES_METALS_CONFIG_CREATE",
    "CRM_STORES_METAL_CONFIG_UPDATE",
    "CRM_STORES_METAL_CONFIG_CREATE",
)
