"""
Aliases for metal APIs: role UI section codes (e.g. CRM_MASTERS_METALS_METALS_RATE_VIEW)
must satisfy legacy @admin_auth codes (e.g. CRM_MASTERS_DAILY_GOLD_RATES_VIEW).
"""

# Each key is a code used in @admin_auth(...); values are additional Permission.code rows to accept.
METAL_PERMISSION_ALIASES: dict[str, tuple[str, ...]] = {
    "CRM_MASTERS_METAL_VIEW": (
        "CRM_MASTERS_METALS_METALS_VIEW",
        "CRM_MASTERS_METALS_METALS_CREATE",
        "CRM_MASTERS_METALS_METALS_UPDATE",
        "CRM_MASTERS_METALS_METALS",
        "CRM_MASTERS_METALS_VIEW",
        "CRM_MASTERS_METALS_CREATE",
        "CRM_MASTERS_METALS_UPDATE",
        "CRM_METALS_VIEW",
        "CRM_METALS",
    ),
    "CRM_MASTERS_DAILY_GOLD_RATES_VIEW": (
        "CRM_MASTERS_METALS_METALS_RATE_VIEW",
        "CRM_MASTERS_METALS_METALS_RATE_CREATE",
        "CRM_MASTERS_METALS_METALS_RATE_UPDATE",
        "CRM_MASTERS_METALS_METALS_RATE",
        "CRM_MASTERS_METALS_RATE_VIEW",
        "CRM_MASTERS_METALS_RATE_CREATE",
        "CRM_MASTERS_METALS_RATE_UPDATE",
        "CRM_METAL_RATE_VIEW",
        "CRM_METAL_RATE",
        "CRM_CONFIGURATION_MASTER_METAL_VIEW",
    ),
    "CRM_MASTERS_DAILY_GOLD_RATES_UPDATE": (
        "CRM_MASTERS_METALS_METALS_RATE_UPDATE",
        "CRM_MASTERS_METALS_METALS_RATE_CREATE",
        "CRM_MASTERS_METALS_RATE_UPDATE",
        "CRM_MASTERS_METALS_RATE_CREATE",
        "CRM_METAL_RATE_UPDATE",
        "CRM_METAL_RATE_CREATE",
    ),
    "CRM_STORES_METAL_CONFIGURATION": (
        "CRM_STORES_METAL_CONFIG_VIEW",
        "CRM_STORES_METAL_CONFIG_CREATE",
        "CRM_STORES_METAL_CONFIG_UPDATE",
        "CRM_STORES_METALS_CONFIG_VIEW",
        "CRM_STORES_METALS_CONFIG_CREATE",
        "CRM_STORES_METALS_CONFIG_UPDATE",
        "CRM_STORES_METAL_CONFIG",
        "CRM_STORES_METAL_RULES_VIEW",
        "CRM_STORES_METAL_RATE_VIEW",
        "CRM_STORES_METAL_RATES_VIEW",
        "CRM_STORES_METALS_RATE_VIEW",
    ),
    "CRM_STORES_METAL_RATE": (
        "CRM_STORES_METAL_RATES_VIEW",
        "CRM_STORES_METAL_RATES_CREATE",
        "CRM_STORES_METAL_RATES_UPDATE",
        "CRM_STORES_METAL_RATES",
        "CRM_STORES_METAL_RATE_VIEW",
        "CRM_STORES_METAL_RATE_UPDATE",
        "CRM_STORES_METAL_RATE_CREATE",
        "CRM_STORES_METALS_RATE_VIEW",
        "CRM_STORES_METALS_RATE_CREATE",
        "CRM_STORES_METALS_RATE_UPDATE",
        "CRM_STORES_DAILY_GOLD_RATES_VIEW",
        "CRM_STORES_DAILY_GOLD_RATES_UPDATE",
        "CRM_STORES_DAILY_GOLD_RATES_CREATE",
        "CRM_STORES_METAL_CONFIG_VIEW",
        "CRM_STORES_METALS_CONFIG_VIEW",
        "CRM_STORES_METAL_CONFIGURATION",
    ),
    "CRM_STORES_METAL_RATE_UPDATE": (
        "CRM_STORES_METAL_RATES_UPDATE",
        "CRM_STORES_METAL_RATES_CREATE",
        "CRM_STORES_METALS_RATE_UPDATE",
        "CRM_STORES_METALS_RATE_CREATE",
        "CRM_STORES_METAL_RATE",
    ),
    "CRM_STORES_METAL_RATES_UPDATE": (
        "CRM_STORES_METAL_RATE_UPDATE",
        "CRM_STORES_METAL_RATE_CREATE",
        "CRM_STORES_METALS_RATE_UPDATE",
        "CRM_STORES_METALS_RATE_CREATE",
        "CRM_STORES_METAL_RATE",
    ),
    "CRM_STORES_METALS_RATE_UPDATE": (
        "CRM_STORES_METAL_RATE_UPDATE",
        "CRM_STORES_METAL_RATES_UPDATE",
        "CRM_STORES_METAL_RATE",
    ),
    "CRM_STORES_METAL_CONFIG": (
        "CRM_STORES_METAL_CONFIGURATION",
        "CRM_STORES_METAL_CONFIG_VIEW",
        "CRM_STORES_METAL_CONFIG_CREATE",
        "CRM_STORES_METAL_CONFIG_UPDATE",
        "CRM_STORES_METALS_CONFIG_VIEW",
        "CRM_STORES_METALS_CONFIG_CREATE",
        "CRM_STORES_METALS_CONFIG_UPDATE",
        "CRM_STORES_METAL_RULES",
        "CRM_STORES_METAL_RATE_VIEW",
        "CRM_STORES_METAL_RATES_VIEW",
        "CRM_STORES_METALS_RATE_VIEW",
    ),
    "CRM_STORES_METAL_RULES": (
        "CRM_STORES_METAL_RULES_VIEW",
        "CRM_STORES_METAL_CONFIGURATION",
        "CRM_STORES_METAL_CONFIG",
    ),
    "CRM_STORES": (
        "CRM_STORES_VIEW",
    ),
    # Section codes used in route guards / role UI (inverse of legacy API codes above)
    "CRM_METALS": (
        "CRM_MASTERS_METALS_METALS",
        "CRM_MASTERS_METALS",
        "CRM_MASTERS_METALS_VIEW",
        "CRM_MASTERS_METALS_CREATE",
        "CRM_MASTERS_METALS_UPDATE",
        "CRM_MASTERS_METAL_VIEW",
    ),
    "CRM_METAL_RATE": (
        "CRM_MASTERS_METALS_METALS_RATE",
        "CRM_MASTERS_METALS_RATE_VIEW",
        "CRM_MASTERS_METALS_RATE_CREATE",
        "CRM_MASTERS_METALS_RATE_UPDATE",
        "CRM_MASTERS_DAILY_GOLD_RATES_VIEW",
        "CRM_CONFIGURATION_MASTER_METAL",
        "CRM_MASTERS_DAILY_GOLD_RATES",
    ),
    "CRM_METAL_RULE": (
        "CRM_MASTERS_GOLD_RATE_RULES_VIEW",
        "CRM_MASTERS_GOLD_RATE_RULES",
        "CRM_MASTERS_METALS_RULE_VIEW",
        "CRM_MASTERS_METALS_RULE_CREATE",
        "CRM_MASTERS_METALS_RULE_UPDATE",
        "CRM_MASTERS_METAL_VIEW",
    ),
}


def expand_metal_permission_codes(code: str) -> tuple[str, ...]:
    normalized = (code or "").strip().upper()
    aliases = METAL_PERMISSION_ALIASES.get(normalized, ())
    return (normalized, *aliases)
