"""
Maps legacy @admin_auth codes to role-UI Permission.code rows (section + _VIEW/_CREATE/_UPDATE).
Keep in sync with Frontend/jewel-admin-suite/src/lib/permission-code-matching.ts
"""

from .metal_permission_codes import METAL_PERMISSION_ALIASES

# Section-level aliases: key = code used in @admin_auth(...); values = DB permission codes to accept.
SECTION_PERMISSION_ALIASES: dict[str, tuple[str, ...]] = {
    # --- Customer ---
    "CRM_CUSTOMER_LIST_VIEW": (
        "CRM_CUSTOMER_LIST",
        "CRM_CUSTOMER_LIST_VIEW",
        "CRM_CUSTOMER_LIST_CREATE",
        "CRM_CUSTOMER_LIST_UPDATE",
        "CRM_CUSTOMER_LIST_DELETE",
    ),
    "CRM_CUSTOMER_KYC_PAN_STATUS_VIEW": (
        "CRM_CUSTOMER_KYC_PAN_STATUS",
        "CRM_CUSTOMER_KYC_PAN_STATUS_VIEW",
        "CRM_CUSTOMER_KYC_PAN_STATUS_APPROVE",
        "CRM_CUSTOMER_KYC_PAN_STATUS_UPDATE",
    ),
    "CRM_CUSTOMER_KYC_PAN_STATUS_APPROVE": (
        "CRM_CUSTOMER_KYC_PAN_STATUS_APPROVE",
        "CRM_CUSTOMER_KYC_PAN_STATUS_UPDATE",
    ),
    # --- Scheme ---
    "CRM_SCHEME_ENROLLMENT_VIEW": (
        "CRM_SCHEME_ENROLLMENT",
        "CRM_SCHEME_ENROLLMENT_VIEW",
        "CRM_SCHEME_ENROLLMENT_CREATE",
        "CRM_SCHEME_ENROLLMENT_UPDATE",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_UPDATE",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS_VIEW",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS_UPDATE",
        "CRM_CUSTOMER_UPCOMING_REMINDERS",
        "CRM_CUSTOMER_UPCOMING_REMINDERS_VIEW",
        "CRM_CUSTOMER_UPCOMING_REMINDERS_CREATE",
        "CRM_CUSTOMER_UPCOMING_REMINDERS_UPDATE",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_VIEW",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_CREATE",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_UPDATE",
        "CRM_REMINDERS",
        "CRM_SCHEME_DASHBOARD",
        "CRM_SCHEME_DASHBOARD_VIEW",
        "CRM_SCHEME_LIST",
        "CRM_SCHEME_LIST_VIEW",
        "CRM_SCHEME_ACTIVE",
        "CRM_SCHEME_ACTIVE_VIEW",
    ),
    "CRM_SCHEME_ENROLLMENT_CREATE": (
        "CRM_SCHEME_ENROLLMENT_CREATE",
        "CRM_SCHEME_ENROLLMENT_UPDATE",
    ),
    "CRM_MASTERS_SCHEME_MASTER_VIEW": (
        "CRM_MASTERS_SCHEME_MASTER",
        "CRM_MASTERS_SCHEME_MASTER_VIEW",
        "CRM_MASTERS_SCHEME_MASTER_CREATE",
        "CRM_MASTERS_SCHEME_MASTER_UPDATE",
        "CRM_MASTERS_SCHEME_MASTER_DELETE",
        "CRM_SCHEME_LIST",
        "CRM_SCHEME_LIST_VIEW",
    ),
    "CRM_MASTERS_SCHEME_MASTER_CREATE": (
        "CRM_MASTERS_SCHEME_MASTER_CREATE",
        "CRM_MASTERS_SCHEME_MASTER_UPDATE",
    ),
    "CRM_MASTERS_SCHEME_MASTER_UPDATE": (
        "CRM_MASTERS_SCHEME_MASTER_UPDATE",
    ),
    "CRM_MASTERS_SCHEME_MASTER_DELETE": (
        "CRM_MASTERS_SCHEME_MASTER_DELETE",
    ),
    # --- Accounts ---
    "CRM_ACCOUNTS_PAYMENT_VERIFICATION_VIEW": (
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION",
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION_VIEW",
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION_CREATE",
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION_UPDATE",
    ),
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE": (
        "CRM_ACCOUNTS_SCHEME_PAYMENTS",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_UPDATE",
        "CRM_SCHEME_ENROLLMENT_CREATE",
    ),
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW": (
        "CRM_ACCOUNTS_SCHEME_PAYMENTS",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_UPDATE",
    ),
    "CRM_ACCOUNTS_INSTALMENT_RECORDS_VIEW": (
        "CRM_ACCOUNTS_INSTALMENT_RECORDS",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS_VIEW",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS_UPDATE",
    ),
    "CRM_ACCOUNTS_COLLECTION_SUMMARY_VIEW": (
        "CRM_ACCOUNTS_COLLECTION_SUMMARY",
        "CRM_ACCOUNTS_COLLECTION_SUMMARY_VIEW",
        "CRM_ACCOUNTS_COLLECTION_SUMMARY_CREATE",
        "CRM_ACCOUNTS_COLLECTION_SUMMARY_UPDATE",
    ),
    "CRM_ACCOUNTS_DAILY_LEDGER_VIEW": (
        "CRM_ACCOUNTS_DAILY_LEDGER",
        "CRM_ACCOUNTS_DAILY_LEDGER_VIEW",
        "CRM_ACCOUNTS_DAILY_BOOK",
        "CRM_ACCOUNTS_DAILY_BOOK_VIEW",
    ),
    "CRM_ACCOUNTS_INSTALMENT_RECORDS_UPDATE": (
        "CRM_ACCOUNTS_INSTALMENT_RECORDS",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS_UPDATE",
        "CRM_ACCOUNTS_INSTALMENT_RECORDS_VIEW",
    ),
    "CRM_ACCOUNTS_INVOICE_VIEW": (
        "CRM_ACCOUNTS_INVOICE",
        "CRM_ACCOUNTS_INVOICE_VIEW",
        "CRM_ACCOUNTS_SALES_INVOICE",
        "CRM_ACCOUNTS_SALES_INVOICE_VIEW",
    ),
    "CRM_ACCOUNTS_INVOICE_UPDATE": (
        "CRM_ACCOUNTS_INVOICE_UPDATE",
        "CRM_ACCOUNTS_SALES_INVOICE_UPDATE",
    ),
    # --- Masters ---
    "CRM_MASTERS_CMS_PAGES_VIEW": (
        "CRM_MASTERS_CMS_PAGES",
        "CRM_MASTERS_CMS_PAGES_VIEW",
        "CRM_MASTERS_CMS_PAGES_CREATE",
        "CRM_MASTERS_CMS_PAGES_UPDATE",
    ),
    "CRM_MASTERS_FAQS_VIEW": (
        "CRM_MASTERS_FAQS",
        "CRM_MASTERS_FAQS_VIEW",
        "CRM_MASTERS_FAQS_CREATE",
        "CRM_MASTERS_FAQS_UPDATE",
    ),
    "CRM_MASTERS_FAQS_DELETE": (
        "faq.delete",
        "CRM_MASTERS_FAQS_DELETE",
        "CRM_MASTERS_FAQS_UPDATE",
    ),
    "CRM_MASTERS_CMS_PAGES_DELETE": (
        "cms_page.delete",
        "CRM_MASTERS_CMS_PAGES_DELETE",
        "CRM_MASTERS_CMS_PAGES_UPDATE",
    ),
    "CRM_MASTERS_HSN_MASTER_VIEW": (
        "CRM_MASTERS_HSN_MASTER",
        "CRM_MASTERS_HSN_MASTER_VIEW",
        "CRM_MASTERS_HSN_MASTER_CREATE",
        "CRM_MASTERS_HSN_MASTER_UPDATE",
        "CRM_MASTERS_HSN_MASTER_DELETE",
    ),
    "CRM_MASTERS_HSN_MASTER_CREATE": (
        "CRM_MASTERS_HSN_MASTER_CREATE",
        "CRM_MASTERS_HSN_MASTER_UPDATE",
    ),
    "CRM_MASTERS_HSN_MASTER_UPDATE": (
        "CRM_MASTERS_HSN_MASTER_UPDATE",
    ),
    "CRM_MASTERS_HSN_MASTER_DELETE": (
        "CRM_MASTERS_HSN_MASTER_DELETE",
    ),
    # --- GRN (Masters) ---
    "CRM_MASTERS_GRN_BATCH": (
        "CRM_MASTERS_GRN_BATCH_VIEW",
        "CRM_MASTERS_GRN_BATCH_CREATE",
        "CRM_MASTERS_GRN_BATCH_UPDATE",
        "CRM_MASTERS_GRN_BATCH_DELETE",
    ),
    "CRM_MASTERS_GRN_BATCH_VIEW": (
        "CRM_MASTERS_GRN_BATCH",
        "CRM_MASTERS_GRN_BATCH_VIEW",
        "CRM_MASTERS_GRN_BATCH_CREATE",
        "CRM_MASTERS_GRN_BATCH_UPDATE",
        "CRM_MASTERS_GRN_BATCH_DELETE",
        "CRM_INVENTORY_BATCH_VIEW",
        "CRM_INVENTORY_BATCH",
    ),
    "CRM_MASTERS_GRN_BATCH_CREATE": (
        "CRM_MASTERS_GRN_BATCH_CREATE",
        "CRM_MASTERS_GRN_BATCH_UPDATE",
    ),
    "CRM_MASTERS_GRN_BATCH_UPDATE": (
        "CRM_MASTERS_GRN_BATCH_UPDATE",
    ),
    "CRM_MASTERS_GRN_BATCH_DELETE": (
        "CRM_MASTERS_GRN_BATCH_DELETE",
    ),
    "CRM_MASTERS_GRN_LOT": (
        "CRM_MASTERS_GRN_LOT_VIEW",
        "CRM_MASTERS_GRN_LOT_CREATE",
        "CRM_MASTERS_GRN_LOT_UPDATE",
        "CRM_MASTERS_GRN_LOT_DELETE",
    ),
    "CRM_MASTERS_GRN_LOT_VIEW": (
        "CRM_MASTERS_GRN_LOT",
        "CRM_MASTERS_GRN_LOT_VIEW",
        "CRM_MASTERS_GRN_LOT_CREATE",
        "CRM_MASTERS_GRN_LOT_UPDATE",
        "CRM_MASTERS_GRN_LOT_DELETE",
    ),
    "CRM_MASTERS_GRN_LOT_CREATE": (
        "CRM_MASTERS_GRN_LOT_CREATE",
        "CRM_MASTERS_GRN_LOT_UPDATE",
    ),
    "CRM_MASTERS_GRN_LOT_UPDATE": (
        "CRM_MASTERS_GRN_LOT_UPDATE",
    ),
    "CRM_MASTERS_GRN_LOT_DELETE": (
        "CRM_MASTERS_GRN_LOT_DELETE",
    ),
    "CRM_MASTERS_GRN_BARCODE": (
        "CRM_MASTERS_GRN_BARCODE_VIEW",
        "CRM_MASTERS_GRN_BARCODE_CREATE",
        "CRM_MASTERS_GRN_BARCODE_UPDATE",
        "CRM_MASTERS_GRN_BARCODE_DELETE",
    ),
    "CRM_MASTERS_GRN_BARCODE_VIEW": (
        "CRM_MASTERS_GRN_BARCODE",
        "CRM_MASTERS_GRN_BARCODE_VIEW",
        "CRM_MASTERS_GRN_BARCODE_CREATE",
        "CRM_MASTERS_GRN_BARCODE_UPDATE",
        "CRM_MASTERS_GRN_BARCODE_DELETE",
        "CRM_INVENTORY_BARCODED_VIEW",
        "CRM_INVENTORY_BARCODED",
        "CRM_INVENTORY_MULTI_PIECE_VIEW",
        "CRM_INVENTORY_MULTI_PIECE",
    ),
    "CRM_MASTERS_GRN_BARCODE_CREATE": (
        "CRM_MASTERS_GRN_BARCODE_CREATE",
        "CRM_MASTERS_GRN_BARCODE_UPDATE",
    ),
    "CRM_MASTERS_GRN_BARCODE_UPDATE": (
        "CRM_MASTERS_GRN_BARCODE_UPDATE",
        "CRM_INVENTORY_BARCODED_UPDATE",
    ),
    "CRM_MASTERS_GRN_BARCODE_DELETE": (
        "CRM_MASTERS_GRN_BARCODE_DELETE",
    ),
    "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING": (
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_VIEW",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_CREATE",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_UPDATE",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_DELETE",
    ),
    "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_VIEW": (
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_VIEW",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_CREATE",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_UPDATE",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_DELETE",
    ),
    "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_CREATE": (
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_CREATE",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_UPDATE",
    ),
    "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_UPDATE": (
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_UPDATE",
    ),
    "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_DELETE": (
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_DELETE",
    ),
    "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT": (
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_VIEW",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_CREATE",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_UPDATE",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_DELETE",
    ),
    "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_VIEW": (
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_VIEW",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_CREATE",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_UPDATE",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_DELETE",
    ),
    "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_CREATE": (
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_CREATE",
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_UPDATE",
    ),
    "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_UPDATE": (
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_UPDATE",
    ),
    "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_DELETE": (
        "CRM_MASTERS_GRN_BULK_IMAGE_IMPORT_DELETE",
    ),
    # --- Inventory (Finished Goods) — section shortcuts ---
    "CRM_INVENTORY_BATCH": (
        "CRM_INVENTORY_BATCH_VIEW",
        "CRM_INVENTORY_BATCH_CREATE",
        "CRM_INVENTORY_BATCH_UPDATE",
        "CRM_INVENTORY_BATCH_DELETE",
    ),
    "CRM_INVENTORY_BATCH_VIEW": (
        "CRM_INVENTORY_BATCH",
        "CRM_INVENTORY_BATCH_VIEW",
        "CRM_INVENTORY_BATCH_CREATE",
        "CRM_INVENTORY_BATCH_UPDATE",
        "CRM_INVENTORY_BATCH_DELETE",
        "CRM_MASTERS_GRN_BATCH_VIEW",
    ),
    "CRM_INVENTORY_BARCODED": (
        "CRM_INVENTORY_BARCODED_VIEW",
        "CRM_INVENTORY_BARCODED_CREATE",
        "CRM_INVENTORY_BARCODED_UPDATE",
        "CRM_INVENTORY_BARCODED_DELETE",
    ),
    "CRM_INVENTORY_BARCODED_VIEW": (
        "CRM_INVENTORY_BARCODED",
        "CRM_INVENTORY_BARCODED_VIEW",
        "CRM_INVENTORY_BARCODED_CREATE",
        "CRM_INVENTORY_BARCODED_UPDATE",
        "CRM_INVENTORY_BARCODED_DELETE",
        "CRM_MASTERS_GRN_BARCODE_VIEW",
    ),
    "CRM_INVENTORY_BARCODED_UPDATE": (
        "CRM_INVENTORY_BARCODED_UPDATE",
        "CRM_MASTERS_GRN_BARCODE_UPDATE",
    ),
    "CRM_INVENTORY_QUANTITY": (
        "CRM_INVENTORY_QUANTITY_VIEW",
        "CRM_INVENTORY_QUANTITY_CREATE",
        "CRM_INVENTORY_QUANTITY_UPDATE",
        "CRM_INVENTORY_QUANTITY_DELETE",
    ),
    "CRM_INVENTORY_QUANTITY_VIEW": (
        "CRM_INVENTORY_QUANTITY",
        "CRM_INVENTORY_QUANTITY_VIEW",
        "CRM_INVENTORY_QUANTITY_CREATE",
        "CRM_INVENTORY_QUANTITY_UPDATE",
        "CRM_INVENTORY_QUANTITY_DELETE",
    ),
    "CRM_INVENTORY_MULTI_PIECE": (
        "CRM_INVENTORY_MULTI_PIECE_VIEW",
        "CRM_INVENTORY_MULTI_PIECE_CREATE",
        "CRM_INVENTORY_MULTI_PIECE_UPDATE",
        "CRM_INVENTORY_MULTI_PIECE_DELETE",
    ),
    "CRM_INVENTORY_MULTI_PIECE_VIEW": (
        "CRM_INVENTORY_MULTI_PIECE",
        "CRM_INVENTORY_MULTI_PIECE_VIEW",
        "CRM_INVENTORY_MULTI_PIECE_CREATE",
        "CRM_INVENTORY_MULTI_PIECE_UPDATE",
        "CRM_INVENTORY_MULTI_PIECE_DELETE",
        "CRM_MASTERS_GRN_BARCODE_VIEW",
    ),
    "CRM_MASTERS_CATEGORIES_VIEW": (
        "CRM_MASTERS_CATEGORIES",
        "CRM_MASTERS_CATEGORIES_VIEW",
        "CRM_MASTERS_PRODUCTS_VIEW",
    ),
    "CRM_MASTERS_CATEGORIES_CREATE": (
        "CRM_MASTERS_CATEGORIES_CREATE",
        "CRM_MASTERS_CATEGORIES_UPDATE",
    ),
    "CRM_MASTERS_CATEGORIES_UPDATE": (
        "CRM_MASTERS_CATEGORIES_UPDATE",
    ),
    "CRM_MASTERS_CATEGORIES_DELETE": (
        "CRM_MASTERS_CATEGORIES_DELETE",
        "CRM_MASTERS_CATEGORIES_UPDATE",
    ),
    "CRM_MASTERS_PRODUCTS_VIEW": (
        "CRM_MASTERS_PRODUCTS",
        "CRM_MASTERS_PRODUCTS_VIEW",
    ),
    "CRM_MASTERS_PRODUCTS_CREATE": (
        "CRM_MASTERS_PRODUCTS_CREATE",
        "CRM_MASTERS_PRODUCTS_UPDATE",
    ),
    "CRM_MASTERS_PRODUCTS_UPDATE": (
        "CRM_MASTERS_PRODUCTS_UPDATE",
    ),
    "CRM_MASTERS_PRODUCTS_DELETE": (
        "CRM_MASTERS_PRODUCTS_DELETE",
        "CRM_MASTERS_PRODUCTS_UPDATE",
    ),
    "CRM_MASTERS_TERMS_CONDITIONS_VIEW": (
        "CRM_MASTERS_TERMS_CONDITIONS",
        "CRM_MASTERS_TERMS_CONDITIONS_VIEW",
        "customer_policy_acceptance.view",
    ),
    "CRM_MASTERS_TERMS_CONDITIONS_CREATE": (
        "CRM_MASTERS_TERMS_CONDITIONS_CREATE",
        "customer_policy_acceptance.create",
    ),
    "CRM_MASTERS_TERMS_CONDITIONS_UPDATE": (
        "CRM_MASTERS_TERMS_CONDITIONS_UPDATE",
        "customer_policy_acceptance.edit",
    ),
    "CRM_MASTERS_TERMS_CONDITIONS_DELETE": (
        "CRM_MASTERS_TERMS_CONDITIONS_DELETE",
        "customer_policy_acceptance.delete",
    ),
    "CRM_MASTERS": (
        "CRM_MASTERS_VIEW",
        "CRM_MASTERS_CATEGORIES",
        "CRM_MASTERS_CATEGORIES_VIEW",
        "CRM_MASTERS_PRODUCTS",
        "CRM_MASTERS_PRODUCTS_VIEW",
        "CRM_MASTERS_TERMS_CONDITIONS",
        "CRM_MASTERS_TERMS_CONDITIONS_VIEW",
        "CRM_MASTERS_LOOKUP",
        "CRM_MASTERS_LOOKUP_VIEW",
        "CRM_MASTERS_STONE_MASTER",
        "CRM_MASTERS_STONE_MASTER_VIEW",
        "CRM_MASTERS_GRN_BATCH",
        "CRM_MASTERS_GRN_BATCH_VIEW",
        "CRM_MASTERS_GRN_LOT",
        "CRM_MASTERS_GRN_LOT_VIEW",
        "CRM_MASTERS_GRN_BARCODE",
        "CRM_MASTERS_GRN_BARCODE_VIEW",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING",
        "CRM_MASTERS_GRN_ATTRIBUTE_MAPPING_VIEW",
    ),
    # --- Stores / POS ---
    "CRM_STORES_POS_VIEW": (
        "CRM_STORES_POS",
        "CRM_STORES_POS_VIEW",
        "CRM_STORES_POS_CREATE",
        "CRM_STORES_POS_UPDATE",
    ),
    "CRM_STORES_POS_CREATE": (
        "CRM_STORES_POS_CREATE",
        "CRM_STORES_POS_UPDATE",
    ),
    "CRM_STORES_POS_UPDATE": (
        "CRM_STORES_POS_UPDATE",
    ),
    # --- Settings ---
    "CRM_SETTINGS_USERS_VIEW": (
        "CRM_SETTINGS_USERS",
        "CRM_SETTINGS_USERS_VIEW",
        "CRM_SETTINGS_USERS_CREATE",
        "CRM_SETTINGS_USERS_UPDATE",
    ),
    "CRM_SETTINGS_ROLES_VIEW": (
        "CRM_SETTINGS_ROLES",
        "CRM_SETTINGS_ROLES_VIEW",
        "CRM_SETTINGS_ROLES_CREATE",
        "CRM_SETTINGS_ROLES_UPDATE",
    ),
    "CRM_SETTINGS_DEPARTMENTS_VIEW": (
        "CRM_SETTINGS_DEPARTMENTS",
        "CRM_SETTINGS_DEPARTMENTS_VIEW",
        "CRM_SETTINGS_DEPARTMENTS_CREATE",
        "CRM_SETTINGS_DEPARTMENTS_UPDATE",
    ),
    # --- Customer reminders / visits (section codes in @admin_auth) ---
    "CRM_CUSTOMER_UPCOMING_REMINDERS": (
        "CRM_CUSTOMER_UPCOMING_REMINDERS_VIEW",
        "CRM_CUSTOMER_UPCOMING_REMINDERS_CREATE",
        "CRM_CUSTOMER_UPCOMING_REMINDERS_UPDATE",
        "CRM_REMINDERS",
        "CRM_SCHEME_ENROLLMENT",
        "CRM_SCHEME_ENROLLMENT_VIEW",
    ),
    "CRM_CUSTOMER_PAST_DUE_REMINDERS": (
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_VIEW",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_CREATE",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_UPDATE",
        "CRM_REMINDERS",
        "CRM_SCHEME_ENROLLMENT",
        "CRM_SCHEME_ENROLLMENT_VIEW",
    ),
    "CRM_CUSTOMER_VISIT_TRACKING": (
        "CRM_CUSTOMER_VISIT_TRACKING_VIEW",
        "CRM_CUSTOMER_VISIT_TRACKING_CREATE",
        "CRM_CUSTOMER_VISIT_TRACKING_UPDATE",
    ),
    "CRM_CUSTOMER_CAMPAIGNS": (
        "CRM_CUSTOMER_CAMPAIGNS_VIEW",
        "CRM_CUSTOMER_CAMPAIGNS_CREATE",
        "CRM_CUSTOMER_CAMPAIGNS_UPDATE",
    ),
    "CRM_ACCOUNTS_REFUNDS": (
        "CRM_ACCOUNTS_REFUNDS_VIEW",
        "CRM_ACCOUNTS_REFUNDS_CREATE",
        "CRM_ACCOUNTS_REFUNDS_UPDATE",
    ),
    "CRM_ACCOUNTS_DAILY_BOOK": (
        "CRM_ACCOUNTS_DAILY_BOOK_VIEW",
        "CRM_ACCOUNTS_DAILY_BOOK_CREATE",
        "CRM_ACCOUNTS_DAILY_BOOK_UPDATE",
        "CRM_ACCOUNTS_DAILY_BOOK_DELETE",
        "CRM_ACCOUNTS_DAILY_LEDGER",
        "CRM_ACCOUNTS_DAILY_LEDGER_VIEW",
    ),
    "CRM_ACCOUNTS_SCHEME_PAYMENTS": (
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
        "CRM_ACCOUNTS_SCHEME_PAYMENTS_UPDATE",
    ),
    "CRM_ACCOUNTS_PAYMENT_VERIFICATION": (
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION_VIEW",
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION_CREATE",
        "CRM_ACCOUNTS_PAYMENT_VERIFICATION_UPDATE",
    ),
    "CRM_SCHEME_DASHBOARD": (
        "CRM_SCHEME_DASHBOARD_VIEW",
        "CRM_SCHEME_LIST",
        "CRM_SCHEME_LIST_VIEW",
        "CRM_SCHEME_ENROLLMENT_VIEW",
    ),
    "CRM_SCHEME_DASHBOARD_VIEW": (
        "CRM_SCHEME_DASHBOARD",
        "CRM_SCHEME_DASHBOARD_VIEW",
        "CRM_SCHEME_LIST",
        "CRM_SCHEME_LIST_VIEW",
        "CRM_SCHEME_ENROLLMENT_VIEW",
    ),
    "CRM_SCHEME_LIST_VIEW": (
        "CRM_SCHEME_LIST",
        "CRM_SCHEME_LIST_VIEW",
        "CRM_SCHEME_ENROLLMENT_VIEW",
        "CRM_MASTERS_SCHEME_MASTER",
        "CRM_MASTERS_SCHEME_MASTER_VIEW",
    ),
    "CRM_ACCOUNTS_DAILY_BOOK_VIEW": (
        "CRM_ACCOUNTS_DAILY_BOOK",
        "CRM_ACCOUNTS_DAILY_BOOK_VIEW",
        "CRM_ACCOUNTS_DAILY_LEDGER",
        "CRM_ACCOUNTS_DAILY_LEDGER_VIEW",
    ),
    "CRM_SCHEME_LIST": (
        "CRM_SCHEME_LIST_VIEW",
        "CRM_SCHEME_LIST_CREATE",
        "CRM_SCHEME_LIST_UPDATE",
        "CRM_MASTERS_SCHEME_MASTER",
        "CRM_MASTERS_SCHEME_MASTER_VIEW",
    ),
    # --- Legacy dotted codes ---
    "LEDGER.VIEW": (
        "ledger.view",
        "LEDGER.VIEW",
        "CRM_ACCOUNTS_DAILY_LEDGER_VIEW",
        "CRM_ACCOUNTS_DAILY_LEDGER",
        "CRM_ACCOUNTS_DAILY_BOOK_VIEW",
    ),
    "FAQ.DELETE": (
        "faq.delete",
        "CRM_MASTERS_FAQS_DELETE",
        "CRM_MASTERS_FAQS_UPDATE",
    ),
    "CMS_PAGE.DELETE": (
        "cms_page.delete",
        "CRM_MASTERS_CMS_PAGES_DELETE",
        "CRM_MASTERS_CMS_PAGES_UPDATE",
    ),
    "CUSTOMER_POLICY_ACCEPTANCE.VIEW": (
        "customer_policy_acceptance.view",
        "CUSTOMER_POLICY_ACCEPTANCE.VIEW",
        "CRM_MASTERS_TERMS_CONDITIONS_VIEW",
        "CRM_MASTERS_TERMS_CONDITIONS",
    ),
    "CUSTOMER_POLICY_ACCEPTANCE.CREATE": (
        "customer_policy_acceptance.create",
        "CRM_MASTERS_TERMS_CONDITIONS_UPDATE",
        "CRM_MASTERS_TERMS_CONDITIONS_CREATE",
    ),
    "CUSTOMER_POLICY_ACCEPTANCE.EDIT": (
        "customer_policy_acceptance.edit",
        "CRM_MASTERS_TERMS_CONDITIONS_UPDATE",
    ),
    "CUSTOMER_POLICY_ACCEPTANCE.DELETE": (
        "customer_policy_acceptance.delete",
        "CRM_MASTERS_TERMS_CONDITIONS_DELETE",
        "CRM_MASTERS_TERMS_CONDITIONS_UPDATE",
    ),
    # --- CRM Communication ---
    "CRM_COMMUNICATION_SEND": (
        "CRM_COMMUNICATION",
        "CRM_COMMUNICATION_SEND",
        "CRM_COMMUNICATION_CREATE",
        "CRM_COMMUNICATION_UPDATE",
        "CRM_CUSTOMER_UPCOMING_REMINDERS",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS",
        "CRM_CUSTOMER_LIST",
    ),
    "CRM_COMMUNICATION_VIEW": (
        "CRM_COMMUNICATION",
        "CRM_COMMUNICATION_VIEW",
        "CRM_COMMUNICATION_SEND",
        "CRM_COMMUNICATION_CREATE",
        "CRM_COMMUNICATION_UPDATE",
        "CRM_CUSTOMER_UPCOMING_REMINDERS",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS",
        "CRM_CUSTOMER_LIST",
        "CRM_CUSTOMER_VISIT_TRACKING",
    ),
    "CRM_CUSTOMER_UPCOMING_REMINDERS": (
        "CRM_CUSTOMER_UPCOMING_REMINDERS",
        "CRM_CUSTOMER_UPCOMING_REMINDERS_VIEW",
        "CRM_SCHEME_ENROLLMENT",
        "CRM_SCHEME_ENROLLMENT_VIEW",
        "CRM_SCHEME_ENROLLMENT_UPDATE",
        "CRM_COMMUNICATION_SEND",
        "CRM_COMMUNICATION_CREATE",
        "CRM_CUSTOMER_LIST",
    ),
    "CRM_CUSTOMER_PAST_DUE_REMINDERS": (
        "CRM_CUSTOMER_PAST_DUE_REMINDERS",
        "CRM_CUSTOMER_PAST_DUE_REMINDERS_VIEW",
        "CRM_SCHEME_ENROLLMENT",
        "CRM_SCHEME_ENROLLMENT_VIEW",
        "CRM_SCHEME_ENROLLMENT_UPDATE",
        "CRM_COMMUNICATION_SEND",
        "CRM_COMMUNICATION_CREATE",
        "CRM_CUSTOMER_LIST",
    ),
}

PERMISSION_ALIASES: dict[str, tuple[str, ...]] = {
    **METAL_PERMISSION_ALIASES,
    **SECTION_PERMISSION_ALIASES,
}

# Module parent codes: any user permission with this prefix satisfies the parent gate.
MODULE_PREFIX_WILDCARDS: dict[str, str] = {
    "CRM_MASTERS": "CRM_MASTERS_",
    "CRM_ACCOUNTS": "CRM_ACCOUNTS_",
    "CRM_CUSTOMER": "CRM_CUSTOMER_",
    "CRM_SETTINGS": "CRM_SETTINGS_",
    "CRM_STORES": "CRM_STORES_",
    "CRM_VRM": "CRM_VRM_",
    "CRM_SCHEME_LIST": "CRM_SCHEME_",
    "CRM_SCHEME_ENROLLMENT": "CRM_SCHEME_ENROLLMENT",
    "CRM_DASHBOARD": "CRM_DASHBOARD",
}


def expand_permission_codes(code: str) -> tuple[str, ...]:
    normalized = (code or "").strip().upper()
    aliases = PERMISSION_ALIASES.get(normalized, ())
    return (normalized, *aliases)


def expand_metal_permission_codes(code: str) -> tuple[str, ...]:
    return expand_permission_codes(code)
