"""
Shared @admin_auth permission tuples aligned with frontend section routes.

Use these when an API is called from more than one module (e.g. customer lookup
from Scheme Payments, Enrollment, and Store POS).
"""

# Customer read / lookup — shared across Customer, Accounts, Scheme, Stores
CUSTOMER_READ_AUTH = (
    "CRM_CUSTOMER_LIST_VIEW",
    "CRM_CUSTOMER_LIST_CREATE",
    "CRM_CUSTOMER_LIST_UPDATE",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
    "CRM_ACCOUNTS_INSTALMENT_RECORDS_VIEW",
    "CRM_ACCOUNTS_COLLECTION_SUMMARY_VIEW",
    "CRM_SCHEME_ENROLLMENT_VIEW",
    "CRM_SCHEME_ENROLLMENT_CREATE",
    "CRM_STORES_POS_VIEW",
    "CRM_STORES_POS_CREATE",
)

CUSTOMER_LOOKUP_AUTH = (
    "CRM_CUSTOMER_LIST_VIEW",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
    "CRM_SCHEME_ENROLLMENT_VIEW",
    "CRM_SCHEME_ENROLLMENT_CREATE",
    "CRM_STORES_POS_VIEW",
    "CRM_STORES_POS_CREATE",
)

CUSTOMER_WRITE_AUTH = (
    "CRM_CUSTOMER_LIST_CREATE",
    "CRM_CUSTOMER_LIST_UPDATE",
)

CUSTOMER_DELETE_AUTH = (
    "CRM_CUSTOMER_LIST_DELETE",
    "CRM_CUSTOMER_LIST_UPDATE",
)

# Scheme dashboard & list screens
SCHEME_DASHBOARD_READ_AUTH = (
    "CRM_SCHEME_DASHBOARD_VIEW",
    "CRM_SCHEME_LIST_VIEW",
    "CRM_SCHEME_ENROLLMENT_VIEW",
)

SCHEME_LIST_READ_AUTH = (
    "CRM_SCHEME_LIST_VIEW",
    "CRM_SCHEME_ENROLLMENT_VIEW",
    "CRM_MASTERS_SCHEME_MASTER_VIEW",
)

# Accounts — instalments & scheme payments
ACCOUNTS_INSTALMENT_READ_AUTH = (
    "CRM_ACCOUNTS_INSTALMENT_RECORDS_VIEW",
    "CRM_ACCOUNTS_INSTALMENT_RECORDS_UPDATE",
    "CRM_SCHEME_ENROLLMENT_VIEW",
)

ACCOUNTS_SCHEME_READ_AUTH = (
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_VIEW",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_UPDATE",
    "CRM_SCHEME_ENROLLMENT_VIEW",
)

ACCOUNTS_SCHEME_WRITE_AUTH = (
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_CREATE",
    "CRM_ACCOUNTS_SCHEME_PAYMENTS_UPDATE",
    "CRM_SCHEME_ENROLLMENT_CREATE",
)

ACCOUNTS_DAILY_BOOK_READ_AUTH = (
    "CRM_ACCOUNTS_DAILY_BOOK_VIEW",
    "CRM_ACCOUNTS_DAILY_LEDGER_VIEW",
)

ACCOUNTS_DAILY_BOOK_WRITE_AUTH = (
    "CRM_ACCOUNTS_DAILY_BOOK_CREATE",
    "CRM_ACCOUNTS_DAILY_BOOK_UPDATE",
)

ACCOUNTS_DAILY_BOOK_DELETE_AUTH = (
    "CRM_ACCOUNTS_DAILY_BOOK_DELETE",
    "CRM_ACCOUNTS_DAILY_BOOK_UPDATE",
)

# Store POS catalogue helpers
STORE_POS_READ_AUTH = (
    "CRM_STORES_POS_VIEW",
    "CRM_STORES_POS_CREATE",
    "CRM_STORES_POS_UPDATE",
    "CRM_CUSTOMER_LIST_VIEW",
)

STORE_POS_WRITE_AUTH = (
    "CRM_STORES_POS_CREATE",
    "CRM_STORES_POS_UPDATE",
)

SCHEME_ENROLLMENT_WRITE_AUTH = (
    "CRM_SCHEME_ENROLLMENT_CREATE",
    "CRM_SCHEME_ENROLLMENT_UPDATE",
)

# Masters — categories & products
MASTERS_CATEGORIES_READ_AUTH = (
    "CRM_MASTERS_CATEGORIES_VIEW",
    "CRM_MASTERS_PRODUCTS_VIEW",
)

MASTERS_CATEGORIES_WRITE_AUTH = (
    "CRM_MASTERS_CATEGORIES_CREATE",
    "CRM_MASTERS_CATEGORIES_UPDATE",
)

MASTERS_CATEGORIES_DELETE_AUTH = (
    "CRM_MASTERS_CATEGORIES_DELETE",
    "CRM_MASTERS_CATEGORIES_UPDATE",
)

MASTERS_PRODUCTS_READ_AUTH = (
    "CRM_MASTERS_PRODUCTS_VIEW",
)

MASTERS_PRODUCTS_WRITE_AUTH = (
    "CRM_MASTERS_PRODUCTS_CREATE",
    "CRM_MASTERS_PRODUCTS_UPDATE",
)

MASTERS_PRODUCTS_DELETE_AUTH = (
    "CRM_MASTERS_PRODUCTS_DELETE",
    "CRM_MASTERS_PRODUCTS_UPDATE",
)
